version: '3.6'

services:
  flxwebapi:
    image: fabreguesm/flxwebapi:2.8.336.1-serverlicenciasv2
    hostname: flxwebapi-talles-flexxus-com-ar
    ports:
      - '5011:5000'
    networks:
      - traefik      
    volumes:
      - 'node_data:/app/data/'
      - 'factura_data:/app/factura_electronica/'
      - 'pdf_data:/app/public/pdf/'            
    deploy:      
      placement:
        constraints: ["${NODE}"]          
    environment:
      - URL_LICENSESERVER=https://licencias.flexxus.com.ar
      - VERSION_LICENCIAS=2
      - SECRET_LICENSESERVER=${SECRET_LICENSESERVER} 
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}    
volumes:
  node_data:
    name: "${SERVICE_NAME}_node-data"
  factura_data:
    name: "${SERVICE_NAME}_factura-data"
  pdf_data:
    name: "${SERVICE_NAME}_pdf-data"    
networks:
  traefik:
    external:
      name: traefik
